### ISSUE TITLE
как можно быстро очистить все данные, чтобы сайт снова спросил первого пользователя?

### ISSUE THREAD

**Issue by mazzy-ax** [asm0dey/school-crm#73]
предположим, я набил всякую фигню
и хотел бы начать тестирование заново.

mvn clean не очищает базу данных
заходить в машину docker-compose_postrgres_1 (кстати, зачем такое длинное имя?)
и вручную давать команду субд - лениво.

как можно быстро очистить все данные,
чтобы сайт снова спросил первого пользователя?

**Comment by asm0dey** [comment]
`docker-compose_postrgres_1` генерируется автоматически, это ж докер компоуз :)

Самым простым путём кажется стопнуть дропнуть контенйер с БД и поднять опять. Типа docker-compose stop.

**Comment by mazzy-ax** [comment]
в этом случае данные остаются.
нашел: удалять с volume.
docker volume rm docker-compose_pgdata

спасибо

**Comment by asm0dey** [comment]
Можно и просто убрать volume оттуда временно
